force-app/main/default/objects/Contact/fields/Schedule_Availability__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Availability__c</fullName>
    <label>Schedule Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>07:00 to 09:00</fullName>
            </value>
            <value>
                <fullName>09:00 to 11:00</fullName>
            </value>
            <value>
                <fullName>11:00 to 13:00</fullName>
            </value>
            <value>
                <fullName>13:00 to 15:00</fullName>
            </value>
            <value>
                <fullName>15:00 to 17:00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Schedule_Days__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Days__c</fullName>
    <label>Schedule Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Technician.recordType-meta.xml
<RecordType>
    <fullName>Technician</fullName>
    <active>true</active>
    <label>Technician</label>
</RecordType>

force-app/main/default/classes/TestGetAvailableTechnicians.cls
@isTest
public class TestGetAvailableTechnicians {

    @TestSetup
    static void setup() {
        Account testAccount = new Account(
        	Name='Test Account'
        );
        Contact testTechnician = new Contact(
            FirstName = 'Juan',
            LastName = 'Vargas',
            Title = 'Technician',
            AccountId = testAccount.Id,
            Phone = '123-456-7890',
            Email = 'juan.vargas@exampleemail29939203.com',
            Schedule_Days__c = 'Monday;Tuesday;Wednesday',
            Schedule_Availability__c = '09:00 to 11:00;11:00 to 13:00;13:00 to 15:00'
        );
        insert testAccount;
        insert testTechnician;
    }
    
    @isTest
    static void testAvailableTechnicians() {
        System.Test.startTest();
        List<Contact> result = DynamicShedulerTechsController.getAvailableTechnicians('Monday', '11:00 to 13:00');
        System.Test.stopTest();
        System.assertEquals(1, result.size(), 'Should be 1');
    }
}