force-app/main/default/objects/Contact/fields/Schedule_Availability__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Availability__c</fullName>
    <label>Schedule Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>07:00 to 09:00</fullName>
            </value>
            <value>
                <fullName>09:00 to 11:00</fullName>
            </value>
            <value>
                <fullName>11:00 to 13:00</fullName>
            </value>
            <value>
                <fullName>13:00 to 15:00</fullName>
            </value>
            <value>
                <fullName>15:00 to 17:00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Schedule_Days__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Days__c</fullName>
    <label>Schedule Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TechniciansHandler.cls
public class TechniciansHandler {
	@InvocableMethod(label = 'Update technicians availability')
    public static List<Contact> updateSchedule(List<Request> requestList) {
    List<Contact> contactsList = requestList[0].contactsList;
    List<Contact> updatedList = new List<Contact>();
    for (Contact targetTechnician : contactsList) {
        String techniciansScheduleTime = targetTechnician.Schedule_Availability__c;
        String techniciansScheduleDay = targetTechnician.Schedule_Days__c;
        List<String> scheduleTimeSet = techniciansScheduleTime.split(';');
        List<String> scheduleDaySet = techniciansScheduleDay.split(';');
        String workOrderDay = requestList[0].workOrderDay;
        String workOrderTime = requestList[0].workOrderTime;
        scheduleTimeSet.add(workOrderTime);
        scheduleDaySet.add(workOrderDay);
        String joinedScheduleTime = String.join(scheduleTimeSet, ';');
        String joinedScheduleDay = String.join(scheduleDaySet, ';');
        targetTechnician.Schedule_Availability__c = joinedScheduleTime;
        targetTechnician.Schedule_Days__c = joinedScheduleDay;
        updatedList.add(targetTechnician);
    }
    UPDATE updatedList;
    return updatedList;
	}

    public class Request {
        @InvocableVariable(required = true)
        public List<Contact> contactsList;
        
        @InvocableVariable(required = true)
        public String workOrderDay;
        
        @InvocableVariable(required = true)
        public String workOrderTime;
    }
}