force-app/main/default/objects/Contact/fields/Schedule_Availability__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Availability__c</fullName>
    <label>Schedule Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>07:00 to 09:00</fullName>
            </value>
            <value>
                <fullName>09:00 to 11:00</fullName>
            </value>
            <value>
                <fullName>11:00 to 13:00</fullName>
            </value>
            <value>
                <fullName>13:00 to 15:00</fullName>
            </value>
            <value>
                <fullName>15:00 to 17:00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Schedule_Days__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Days__c</fullName>
    <label>Schedule Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DynamicShedulerTechsController.cls
public class DynamicShedulerTechsController {
    @AuraEnabled(cacheable=true)
    public static List<Contact> getAvailableTechnicians(String scheduleDay, String scheduleTime) {
        List<Contact> technicians = [SELECT Id, Title, AccountId, Phone, Email, Name FROM Contact WHERE (Schedule_Days__c INCLUDES(:scheduleDay) AND Schedule_Availability__c INCLUDES(:scheduleTime))];
        return technicians;
    }
}